package com.officework.constants;

/**
 * Created by girish.sharma on 7/28/2016.
 */
public enum Extras {
    SELECTED_SUBCATEGORY, SELECTED_CONTENT, SELECTED_DATE, TITLE, ORIGINAL_AUDIO_PATH, RECORDED_AUDIO_PATH, FILEPATH, SELECTED_POSITION, CROPPER_REQUEST_TYPE, CROPPER_IMAGE_PATH, CROPPED_BITMAP, EXTRA_PASSCODE, ENTRY_POINT_PASSCODE, QUESTION, SELECTED_CATEGORY

}
