package com.officework.constants;

/**
 * Created by girish.sharma on 7/28/2016.
 */

public enum FragmentTag {

    /**
     * Tag names for fragments
     */
    HEADER_FRAGMENT, DASHBOARD_FRAGMENT, DEVICE_INFO_FRAGMENT, HARDWARE_INFO_FRAGMENT, SYSTEM_INFO_FRAGMENT, BATTERY_INFO_FRAGMENT,
    NETWORK_INFO_FRAGMENT, CAMERA_INFO_FRAGMENT, VIBRATE_AUTOMATED_TEST, AUTOMATED_TEST_FRAGMENT,SUMMARY_FRAGMENT, MANUAL_TEST_FRAGMENT,
    CAMERA_FRAGMENT, EAR_JACK_FRAGMENT, VOLUME_BUTTON_FRAGMENT, POWER_BUTTON_FRAGMENT, CHARGING_PORT_FRAGMENT, DISPLAY_FRAGMENT, MUTITOUCH_FRAGMENT, PROXIMITY_SENSOR_FRAGMENT,
    SCREEN_TOUCH_FRAGMENT, HOME_FRAGMENT, SLEEP_WAKE_FRAGMENT, LIGHT_SENSOR_FRAGMENT, COMPASS_FRAGMENT, AUTOMATION_TEST_FRAGMENT,CALL_FUNCTION_FRAGMENT, GPS_FRAGMENT, PHONE_SHAKE_FRAGMENT, ABOUT_US_FRAGMENT, GETQRCODE_FRAGMENT, MIC_TEST_FRAGMENT, MIC_MANUAL_FRAGMENT, SPEAKER_MANUAL_FRAGMENT, TITLE_BAR, NAVIGATION_DRAWER, SPLASH_SCREEN, EXPERT_MODE_FRAGMENT, EXCEPTIONTABLEFRAGMENT, EXCEPTIONDETAILFRAGMENT, MANUAL_TOTAL_TESTS_FRAGMENT, SEMI_AUTOMATIC_TESTS_FRAGMENT, COMPLETE_ORDER_CHANNEL_LOGIN, DEVICE_CASING_FRAGMENT,FLASH_TEST_FRAGMENT,COMPASS_TEST_FRAGMENT,FINGERPRINT_TEST_FRAGMENT,ACCELEROMETER_TEST_FRAGMENT,FACEDETECTION_TEST_FRAGMENT,BAROMETER_TEST_FRAGMENT,MIC_SPEAKER_MANUAL_FRAGMENT;

}
